name: ci-goland-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    strategy:
      matrix:
        go: ['1.14', '1.15']
    runs-on: ubuntu-latest
    steps:
      # Pega os dados e baixa os arquivos para a VM
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go